Feature/david fibonacci 01
agonsant/curso-ultima-milla pull request #1
Opened 2022-06-14 15:47 UTC by DavidGalGom

2022-06-14 16:04 UTC, DavidGalGom commented
One question, I don't know if is needed put the file `package-lock.json` inside the .gitignore

2022-06-17 14:15 UTC, agonsant requested changes
Hey David your are awsome!. I need this project to be wrapper into a folder with name for example `typescript-exercises` because we will create isolated projects in the future

2022-06-17 14:15 UTC, agonsant commented on students/david/src/01-fibonacci/index.ts
> +let numberOfIterations:number;
You could merge declaration and assign of those variables and change it to const instead of let

2022-06-17 14:15 UTC, agonsant commented on students/david/src/01-fibonacci/iterativeFibonacci.ts
> +const iterativeFibonacci = (number:number):bigint => {
missing docs. Public API should be documented using JSDoc or somethin similar. The code should be selfcommented

2022-06-17 14:15 UTC, agonsant commented on students/david/src/01-fibonacci/recursiveFibonacci.ts
> +const recursiveFibonacci = (number:number):bigint => {
missing docs as iterative

2022-06-17 14:15 UTC, agonsant commented on students/david/src/01-fibonacci/recursiveFibonacci.ts
> + * TOTAL: ==> O(X^n)
in this case we know X, it is 2

2022-06-17 14:15 UTC, agonsant commented on students/david/src/01-fibonacci/__tests__/iterativeFibonacci.spec.ts
> +  describe('When is called with a 0', () => {
this and next test cases are coupled to value definition. Maybe it should be renamed to somethin like:

`When is called with a base case, it should return its base value` or  the others `when is called with a small positive number, it should return it fib value` and another test case `when is called with a big positive number it should return its fib value`. 
With this definition we cover functional cases not value cases

2022-06-20 09:02 UTC, DavidGalGom commented
I just fixed all the requested changes

2022-06-20 16:28 UTC, merged